; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = nordicnrf52
board = nrf52840_dk
framework = arduino

monitor_speed = 115200
board_build.ldflags = 
    -Wl,--defsym=__stack_size__=0x8000
    -Wl,--defsym=__heap_size__=0x8000

build_flags = 
    -DARDUINO_ARDUINO_NANO33BLE 
    -DARDUINO_ARCH_NRF52840
    -DNOMINMAX
    -DTF_LITE_USE_GLOBAL_ROUND=0
    -std=gnu++17
    -Ilib/tflm_tree
    -Ilib/tflm_tree/tensorflow
    -Ilib/tflm_tree/tensorflow/lite
    -Ilib/tflm_tree/tensorflow/lite/micro
    -Ilib/tflm_tree/tensorflow/lite/micro/kernels/
    
    ; The tensorflowlite-micro third party library paths
    -Ilib/tflm_tree/third_party/flatbuffers/include
    -Ilib/tflm_tree/third_party/gemmlowp
    -Ilib/tflm_tree/third_party/kissfft
    -Ilib/tflm_tree/third_party/ruy
    -DTF_LITE_STATIC_MEMORY
    -DTF_LITE_DISABLE_X86_NEON
    -mcpu=cortex-m4
    -mthumb
    -mfpu=fpv4-sp-d16
    -DARM_MATH_CM4
    -DARM_MATH_DSP
    -D__FPU_PRESENT=1
    -DCMSIS_NN
    -O3
    -DNDEBUG
    -fno-exceptions
    -ffunction-sections
    -fdata-sections

[env:kws_large]
extends = env
build_flags = 
    ${env.build_flags}
    -Isrc/kws_large
build_src_filter = 
    +<*>
    -<kws_small/>
    -<person_detection/>
    -<vww>

[env:kws_small]
extends = env
build_flags = 
    ${env.build_flags}
    -Isrc/kws_small
build_src_filter = 
    +<*>
    -<kws_large/>
    -<person_detection/>
    -<vww>

[env:person_detection]
extends = env
build_flags = 
    ${env.build_flags}
    -Isrc/person_detection
build_src_filter = 
    +<*>
    -<kws_large/>
    -<kws_small/>
    -<vww>

[env:vww]
extends = env
build_flags = 
    ${env.build_flags}
    -Isrc/vww
build_src_filter = 
    +<*>
    -<kws_large/>
    -<kws_small/>
    -<person_detection>
