[platformio]
default_envs = nano33ble
extra_configs = private_config.ini

[env]
framework = arduino
monitor_speed = 115200

; Arduino Nano 33 BLE
[env:nano33ble]
extends = env
platform = nordicnrf52
board = nano33ble
lib_deps = 
    arduino-libraries/ArduinoBLE
lib_ignore = 
    WiFi

; Raspberry Pi Pico W
[env:pico]
extends = env
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipicow
board_build.core = earlephilhower
build_flags = 
    -D ARDUINO_RASPBERRY_PI_PICO_W
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_BLUETOOTH
    ${env.build_flags}
lib_deps = 
    WiFi
    BTstackLib

[env:pico2]
extends = env:pico
board = rpipico2w
build_flags = 
    -D ARDUINO_RASPBERRY_PI_PICO_2W
    -D ARDUINO_ARCH_RP2350
    -D PICO_RP2350=1
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_BLUETOOTH
    ${env.build_flags}
    
; TinyPICO (ESP32)
[env:tinypico]
extends = env
platform = espressif32
board = tinypico
board_build.partitions = huge_app.csv
lib_deps = 
    WiFi