import streamlit as st
import numpy as np

from constants import * 
from helper import *

def run_hybrid_powered_analysis(
    workload_df,
    workload,
    irradiance,
    inference_per_second,
    solar_panel_area_cap,
    lifetime_years,
    streamlit_plot = True
):
    # ==========================================
    # Dataframe Calculations
    # ==========================================

    workload_df["hybrid duty cycle (%)"] = (
        (workload_df["Total Processing Time (us)"] / 1e6) * inference_per_second
    ) * 100 

    workload_df_hybrid = workload_df[workload_df["hybrid duty cycle (%)"] <= 100].copy()

    # Calculate the energy stored in capacitors (in Joules)
    workload_df_hybrid["energy in capacitors (mJ)"] = workload_df_hybrid.apply(
        lambda row: calculate_energy_in_capacitors(
            row["number of capacitors"], row["Vh"], row["Vl"]
        ),
        axis=1
    )

    # calculate solar panel area required for inference frequency
    workload_df_hybrid["solar panel area (cm2)"] = workload_df_hybrid["inference energy (mJ)"].apply(
        lambda x: calculate_solar_panel_area(x, irradiance=irradiance, inference_per_second=inference_per_second )
    )

    # limit the solar panel area to the user defined max area
    workload_df_hybrid["solar panel area capped (cm2)"] = workload_df_hybrid["solar panel area (cm2)"].apply(
        lambda x: min(x, solar_panel_area_cap)
    )

    # for the device that cannot run the workload with solar panel area cap, calculate the the percentage of inference powered by solar
    # 1. calculate the amount of power generated by the solar panel based on area, irradiance, and efficiency
    # 2. convert that amount of power to energy per second
    # 3. calculate the percentage of inference energy that can be powered by solar 
    # 4. calculate the amount energy that need to be provided by battery per second
    workload_df_hybrid["solar energy per second (mJ)"] = (
        workload_df_hybrid["solar panel area capped (cm2)"] * irradiance * solar_panel_efficiency * 1e-3  
    )
    # print("workload_df['solar energy per second (mJ)']:\n", workload_df["solar energy per second (mJ)"])    
    
    workload_df_hybrid["solar charging time per inference (s)"] = workload_df_hybrid.apply(
        lambda row: calculate_charging_time_per_inference(
            row["energy in capacitors (mJ)"],
            row["solar panel area capped (cm2)"],
            irradiance=irradiance
        ),
        axis=1
    )

    workload_df_hybrid["number of inferences powered by solar per second"] = workload_df_hybrid["solar energy per second (mJ)"] / workload_df_hybrid["inference energy (mJ)"]

    workload_df_hybrid["number of capacitor sets"] = workload_df_hybrid["Total Processing Time (us)"] * 1e-6 / workload_df_hybrid["solar charging time per inference (s)"] + 1

    workload_df_hybrid["battery energy per second (mJ)"] = (
         workload_df_hybrid["inference energy (mJ)"] * inference_per_second - workload_df_hybrid["solar energy per second (mJ)"]
    )

    workload_df_hybrid["battery per second (AA)"] = workload_df_hybrid["battery energy per second (mJ)"] / 1000.0 / AA_energy

    # calculate the number of batteries needed for the deployment lifetime
    workload_df_hybrid["batteries needed over lifetime"] = (
        workload_df_hybrid["battery per second (AA)"] * 60 * 60 * 24 * 365 * lifetime_years
    )
    # calculate the embodied carbon for batteries
    workload_df_hybrid["hybrid battery carbon over lifetime (kg CO2e)"] = (
        workload_df_hybrid["batteries needed over lifetime"] * AA_carbon
    )

    workload_df_hybrid["solar panel capped embodied carbon (kg CO2e)"] = (
        workload_df_hybrid["solar panel area capped (cm2)"] * solar_panel_emission_per_cm2
    )

    workload_df_hybrid["kg CO2e (board)"] = workload_df_hybrid["Devices"].map(whole_board_carbon)
    workload_df_hybrid["kg CO2e (voltage regulator)"] = workload_df_hybrid["Devices"].map(voltage_regulator_CO2)
    workload_df_hybrid["kg CO2e (capacitor only)"] = (
        workload_df_hybrid["kg CO2e (capacitor only)"] * workload_df_hybrid["number of capacitor sets"] * lifetime_years * 12 # 12 months
    )
    workload_df_hybrid["kg CO2e (switches only)"] = capacitor_switches_CO2e * (workload_df_hybrid["number of capacitor sets"] - 1)

    # calculate monetary cost for hybrid power mode
    workload_df_hybrid["solar panel cost ($)"] = (
        workload_df_hybrid["solar panel area capped (cm2)"] * solar_panel_per_cm2_cost
    )
    workload_df_hybrid["capacitor cost ($)"] = (
        workload_df_hybrid["number of capacitors"] * workload_df_hybrid["number of capacitor sets"] * per_capacitor_cost
    )

    workload_df_hybrid["board cost ($)"] = workload_df_hybrid["Devices"].map(monetary_cost)
    workload_df_hybrid["voltage regulator cost ($)"] = workload_df_hybrid["Devices"].map(voltage_regulator_cost)
    workload_df_hybrid["battery cost ($)"] = (
        workload_df_hybrid["batteries needed over lifetime"] * AA_battery_cost
    )
    workload_df_hybrid["switches cost ($)"] = (
        (workload_df_hybrid["number of capacitor sets"] - 1) * capacitor_switches_cost
    )

    # Calculate total embodied carbon
    workload_df_hybrid["total embodied carbon (kg CO2e)"] = (
        workload_df_hybrid["kg CO2e (capacitor only)"]
        + workload_df_hybrid["solar panel capped embodied carbon (kg CO2e)"]
        + workload_df_hybrid["kg CO2e (board)"]
        + workload_df_hybrid["kg CO2e (voltage regulator)"]
        + workload_df_hybrid["hybrid battery carbon over lifetime (kg CO2e)"]
        + workload_df_hybrid["kg CO2e (switches only)"]
    )

    # calculate total monetary cost
    workload_df_hybrid["total monetary cost ($)"] = (
        workload_df_hybrid["capacitor cost ($)"]
        + workload_df_hybrid["solar panel cost ($)"]
        + workload_df_hybrid["board cost ($)"]
        + workload_df_hybrid["voltage regulator cost ($)"]
        + workload_df_hybrid["battery cost ($)"]
        + workload_df_hybrid["switches cost ($)"]
    )

    # ===============================
    # Carbon Emission Stacked Bar Chart Plot (hybrid powered)
    # ===============================

    # plot the stacked multi-bar chart for hybrid power mode
    # solar panel, capacitor, board, voltage regulator, and battery
    if streamlit_plot:
        st.subheader(f"Embodied Carbon for {workload} (Hybrid Power Mode)")
    fig, ax = plt.subplots(figsize=(5, 3))
    components = [
        "kg CO2e (capacitor only)",
        "solar panel capped embodied carbon (kg CO2e)",
        "kg CO2e (board)",
        "kg CO2e (voltage regulator)",
        "hybrid battery carbon over lifetime (kg CO2e)",
        "kg CO2e (switches only)"
    ]
    pad = 0.01
    colors = map_components_to_colors(components)
    workload_df_hybrid.set_index("Devices")[components].plot(
        kind='bar', stacked=True, ax=ax, color=colors
    )
    for i, row in workload_df_hybrid.reset_index().iterrows():
        total_height = row[components].sum()
        duty_cycle = row["battery duty cycle (%)"] + row["solar duty cycle (%)"]
        area_cm2 = row["solar panel area capped (cm2)"]
        caps = row.get("number of capacitors", None) * row.get("number of capacitor sets", 1) * 2 # we need to have two sets of capcitors to support "non-stop" inference, so we multiply by 2 to get the total number of capacitors used in the system.

        # Build a multi-line label
        label_lines = [
            f"{total_height:.3f} kg",  # total embodied carbon
            # f"{duty_cycle:.1f}%",              # duty cycle
            f"{area_cm2:.2f} cm²",             # solar panel area
        ]
        label = "\n".join([s for s in label_lines if s])

        ax.text(
            i, total_height + pad,
            label,
            ha='center', va='bottom', fontsize=9,
        )
    ax.set_ylim(0, max(workload_df_hybrid[components].sum(axis=1)) * 1.25)
    ax.set_xticklabels(workload_df_hybrid["Devices"], rotation=20)
    ax.set_ylabel("Embodied Carbon (kg CO2e)")
    ax.legend(["Capacitors", "Solar Panel", "Board", "Voltage Regulator", "Battery", "Switches"], bbox_to_anchor=(0.5, 1.25), loc='upper center', ncol=4)
    if streamlit_plot:
        st.pyplot(fig)
    if GENERATE_PLOTS:
        fig.savefig("figures/hybrid_powered_embodied_carbon.pdf", dpi=300)

    # ===============================
    # Cost Stacked Bar Chart Plot  (hybrid powered)
    # ===============================
    if streamlit_plot:
        st.subheader(f"Monetary Cost for {workload} (Hybrid Power Mode)")
    fig, ax = plt.subplots(figsize=(5, 4))

    components = [
        "capacitor cost ($)",
        "solar panel cost ($)",
        "board cost ($)",
        "voltage regulator cost ($)",
        "battery cost ($)",
        "switches cost ($)"
    ]
    colors = map_components_to_colors(components)
    workload_df_hybrid.set_index("Devices")[components].plot(
        kind='bar', stacked=True, ax=ax, color=colors, width=0.8
    )
    # add labels on top of bars: Duty cycle, number of batteries per day
    pad = 0.01  # vertical padding above the bar (in y-axis units)
    workload_df_hybrid_reset = workload_df_hybrid.reset_index(drop=True)
    total_heights_list = []
    for i, row in workload_df_hybrid_reset.iterrows():
        total_height = row[components].sum()
        total_heights_list.append(total_height)
        duty_cycle = row["battery duty cycle (%)"] + row["solar duty cycle (%)"]
        area_cm2 = row["solar panel area capped (cm2)"]
        batteries_per_day = row["batteries needed over lifetime"] / (lifetime_years * 365)

        # Build a multi-line label
        label_lines = [
            f"${total_height:.0f}",  # total cost
            # f"{duty_cycle:.1f}%",              # duty cycle
            # f"{area_cm2/10000:.2f} m²",             # solar panel area
            # f"{batteries_per_day:.2f} AA battery/day" # batteries per day
        ]
        label = "\n".join([s for s in label_lines if s])

        ax.text(
            i, total_height + pad,
            label,
            ha='center', va='bottom', fontsize=9, fontweight='bold'
        )
    # Final plot polish
    ymin, ymax = ax.get_ylim()
    ax.set_ylim(ymin, max(total_heights_list) * 1.25)
    ax.set_ylabel("Monetary Cost ($)")
    ax.set_xticklabels(workload_df_hybrid["Devices"], rotation=20, fontsize=10, weight='bold')
    ax.set_yticklabels([f"{int(tick)}" for tick in ax.get_yticks()], rotation=90, va='center')
    ax.legend(["Capacitors", "Solar Panel", "Board", "Voltage Regulator", "Battery"], bbox_to_anchor=(0.5, 1.3), loc='upper center', ncol=4)
    plt.tight_layout()
    if streamlit_plot:
        st.pyplot(fig)
    if GENERATE_PLOTS:
        fig.savefig("figures/hybrid_powered_cost.pdf", dpi=300)

    return workload_df_hybrid


